// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Gender Gender Gender Gender Gender Gender Gender Gender Gender gender
// swagger:model Gender
type Gender struct {

	// female
	Female bool `json:"female,omitempty"`

	// gender non binary
	GenderNonBinary bool `json:"genderNonBinary,omitempty"`

	// male
	Male bool `json:"male,omitempty"`

	// transgender
	Transgender bool `json:"transgender,omitempty"`
}

// Validate validates this gender
func (m *Gender) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Gender) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Gender) UnmarshalBinary(b []byte) error {
	var res Gender
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
