// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LoginUserRequestOKBody LoginUserRequestOKBody LoginUserRequestOKBody LoginUserRequestOKBody login user request o k body
// swagger:model LoginUserRequestOKBody
type LoginUserRequestOKBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// Jwt Token
	// Required: true
	JwtToken *string `json:"token"`
}

// Validate validates this login user request o k body
func (m *LoginUserRequestOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJwtToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LoginUserRequestOKBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("error", "body", m.Error); err != nil {
		return err
	}

	return nil
}

func (m *LoginUserRequestOKBody) validateJwtToken(formats strfmt.Registry) error {

	if err := validate.Required("token", "body", m.JwtToken); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LoginUserRequestOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginUserRequestOKBody) UnmarshalBinary(b []byte) error {
	var res LoginUserRequestOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
