// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserRequestParams creates a new GetUserRequestParams object
// with the default values initialized.
func NewGetUserRequestParams() *GetUserRequestParams {
	var ()
	return &GetUserRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserRequestParamsWithTimeout creates a new GetUserRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserRequestParamsWithTimeout(timeout time.Duration) *GetUserRequestParams {
	var ()
	return &GetUserRequestParams{

		timeout: timeout,
	}
}

// NewGetUserRequestParamsWithContext creates a new GetUserRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserRequestParamsWithContext(ctx context.Context) *GetUserRequestParams {
	var ()
	return &GetUserRequestParams{

		Context: ctx,
	}
}

// NewGetUserRequestParamsWithHTTPClient creates a new GetUserRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserRequestParamsWithHTTPClient(client *http.Client) *GetUserRequestParams {
	var ()
	return &GetUserRequestParams{
		HTTPClient: client,
	}
}

/*GetUserRequestParams contains all the parameters to send to the API endpoint
for the get user request operation typically these are written to a http.Request
*/
type GetUserRequestParams struct {

	/*Body
	  user account to create

	*/
	Body GetUserRequestBody
	/*ID
	  The id of the product for which the operation relates

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user request params
func (o *GetUserRequestParams) WithTimeout(timeout time.Duration) *GetUserRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user request params
func (o *GetUserRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user request params
func (o *GetUserRequestParams) WithContext(ctx context.Context) *GetUserRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user request params
func (o *GetUserRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user request params
func (o *GetUserRequestParams) WithHTTPClient(client *http.Client) *GetUserRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user request params
func (o *GetUserRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get user request params
func (o *GetUserRequestParams) WithBody(body GetUserRequestBody) *GetUserRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get user request params
func (o *GetUserRequestParams) SetBody(body GetUserRequestBody) {
	o.Body = body
}

// WithID adds the id to the get user request params
func (o *GetUserRequestParams) WithID(id int64) *GetUserRequestParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get user request params
func (o *GetUserRequestParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
