// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoginUserRequestParams creates a new LoginUserRequestParams object
// with the default values initialized.
func NewLoginUserRequestParams() *LoginUserRequestParams {
	var ()
	return &LoginUserRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoginUserRequestParamsWithTimeout creates a new LoginUserRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoginUserRequestParamsWithTimeout(timeout time.Duration) *LoginUserRequestParams {
	var ()
	return &LoginUserRequestParams{

		timeout: timeout,
	}
}

// NewLoginUserRequestParamsWithContext creates a new LoginUserRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoginUserRequestParamsWithContext(ctx context.Context) *LoginUserRequestParams {
	var ()
	return &LoginUserRequestParams{

		Context: ctx,
	}
}

// NewLoginUserRequestParamsWithHTTPClient creates a new LoginUserRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoginUserRequestParamsWithHTTPClient(client *http.Client) *LoginUserRequestParams {
	var ()
	return &LoginUserRequestParams{
		HTTPClient: client,
	}
}

/*LoginUserRequestParams contains all the parameters to send to the API endpoint
for the login user request operation typically these are written to a http.Request
*/
type LoginUserRequestParams struct {

	/*Body*/
	Body LoginUserRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the login user request params
func (o *LoginUserRequestParams) WithTimeout(timeout time.Duration) *LoginUserRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login user request params
func (o *LoginUserRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login user request params
func (o *LoginUserRequestParams) WithContext(ctx context.Context) *LoginUserRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login user request params
func (o *LoginUserRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login user request params
func (o *LoginUserRequestParams) WithHTTPClient(client *http.Client) *LoginUserRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login user request params
func (o *LoginUserRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the login user request params
func (o *LoginUserRequestParams) WithBody(body LoginUserRequestBody) *LoginUserRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the login user request params
func (o *LoginUserRequestParams) SetBody(body LoginUserRequestBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *LoginUserRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
