admin:
  port: 9991

namers: []
storage:
  kind: io.l5d.inMemory
  namespaces:
    default: |
      /host/business_account_service           => /$/inet/business_account_service/9898;
      /grpc               => /host;
      /svc                => /host/business_account_service;
interfaces:
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180
