{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "authentication_handler_service.fullname" . }}-redis
data:
  redis.conf: |
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
{{- end }}
