version: '3.7'

services:
  # business_account_service for the blackspace platform
  business_account_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: business_account_service
    ports:
      - "9898:9898"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - '.:/go/src/github.com/BlackspaceInc/BlackspacePlatform/src/services/business_account_service'
    depends_on:
      - business_account_service_db

  business_account_service_db:
    container_name: business_account_service_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - net

  pgadmin-compose:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT_EXTERNAL}:${PGADMIN_PORT_INTERNAL}"
    networks:
      - net
    depends_on:
      - business_account_service_db

networks:
  net:
    driver: bridge

volumes:
  postgres:
