version: '3.7'

services:
  # business_account_service for the blackspace platform
  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: business_account_service
    ports:
      - "9898:9898"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - '.:/go/src/github.com/BlackspaceInc/BlackspacePlatform/src/services/business_account_service'

networks:
  net:
    driver: bridge
