// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateBusinessAccountRequest) Validate() error {
	if this.BusinessAccount != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BusinessAccount); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BusinessAccount", err)
		}
	}
	return nil
}
func (this *UpdateBusinessAccountRequest) Validate() error {
	if this.UpdatedBusinessAccount != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedBusinessAccount); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedBusinessAccount", err)
		}
	}
	return nil
}
func (this *DeleteBusinessAccountRequest) Validate() error {
	return nil
}
func (this *GetBusinessAccountRequest) Validate() error {
	return nil
}
func (this *GetBusinessAccountsRequest) Validate() error {
	return nil
}
func (this *ResponseStatus) Validate() error {
	return nil
}
