apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: webapp
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: frontend
    spec:
      serviceAccountName: webapp
      containers:
      - name: frontend
        image: blackspaceinc/shopper_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9896
          protocol: TCP
        - name: http-metrics
          containerPort: 9796
          protocol: TCP
        - name: grpc
          containerPort: 9996
          protocol: TCP
        command:
        - ./shopper_service
        - --port=9896
        - --port-metrics=9796
        - --level=info
        - --backend-url=http://backend:9896/echo
        env:
        - name: shopper_service_UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9896/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9896/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
