// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: models/schema.proto

package models

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Company) Validate() error {
	if this.PhoneNumber != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PhoneNumber); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PhoneNumber", err)
		}
	}
	if this.Media != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Media); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Media", err)
		}
	}
	if this.TypeOfBusiness != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.TypeOfBusiness); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("TypeOfBusiness", err)
		}
	}
	if this.PaymentDetails != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PaymentDetails); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PaymentDetails", err)
		}
	}
	if this.FounderAddress != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FounderAddress); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FounderAddress", err)
		}
	}
	if this.SubscribedTopics != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SubscribedTopics); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SubscribedTopics", err)
		}
	}
	return nil
}
func (this *Topics) Validate() error {
	return nil
}
func (this *Media) Validate() error {
	return nil
}
func (this *Address) Validate() error {
	if this.Birthdate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Birthdate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Birthdate", err)
		}
	}
	return nil
}
func (this *DateOfBirth) Validate() error {
	return nil
}
func (this *PaymentProcessingMethods) Validate() error {
	return nil
}
func (this *BusinessType) Validate() error {
	return nil
}
func (this *PhoneNumber) Validate() error {
	return nil
}
