{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "business_account_service.serviceAccountName" . }}
  labels:
    {{- include "business_account_service.labels" . | nindent 4 }}
{{- end -}}
