on: push
name: Authentication Handler Service
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/authentication_handler_service
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Validate Helm chart
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            helmv3 template ./charts/authentication_handler_service | kubeval --strict
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            kustomize build ./kustomize | kubeval --strict
            kustomize build ./kustomize | conftest test -p .github/policy -
      - name: Integration & Unit Test Cases
        run: make test-suite
