on: push
name: Authentication Handler Service
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/authentication_handler_service
    steps:
      - uses: actions/checkout@master
      - name: Integration & Unit Test Cases
        run: make test-suite
