name: Business Account Service Static Check
on: push

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/business_account_service
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.ACTION_TOKEN }}
  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/business_account_service
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: errcheck
          token: ${{ secrets.ACTION_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/business_account_service
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint
          token: ${{ secrets.ACTION_TOKEN }}
  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/business_account_service
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          token: ${{ secrets.ACTION_TOKEN }}
  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/business_account_service
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: staticcheck
          token: ${{ secrets.ACTION_TOKEN }}
  sec:
    name: Sec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/business_account_service
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: sec
          token: ${{ secrets.ACTION_TOKEN }}
          flags: "-exclude=G104"
