on: push
name: Blackspace Core
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "./src/libraries/core"
          GO111MODULE: "on"
        with:
          args: make run-tests
      - name: run database tests
        working-directory: ./src/libraries/core/core-database
        run: |
          docker-compose -f compose/docker-compose.postgres.yaml up --build --force-recreate --no-deps -d
          sh -c "echo waiting 10s to let database start... && sleep 10"
          go test -v -race -cover -coverprofile=prof.out ./...
          docker-compose -f compose/docker-compose.postgres.yaml down
