on: push
name: Blackspace Core
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Branch
          uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/checkout@master
      - name: run
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "./src/libraries/core"
          GO111MODULE: "on"
        with:
          args: make run-tests
      - name: Run database tests
          working-directory: ./src/libraries/core-database
          continue-on-error: true
          run: make test
