name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your 1st issue! We are so excited you are passionate about Blackspace!'' Welcome!'
        pr-message:  'Thank you for submitting your 1st pull request! We are so excited you are passionate about Blackspace!'' Welcome!' 
