name: docs


on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
      
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: talos-systems/conform@v0.1.0-alpha.20

