name: docs


on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

repos:
  - repo: https://github.com/talos-systems/conform
    rev: master
    hooks:
      - id: conform
        stages:
          - commit-msg